"""PDF export for the multi-agent research pipeline.

Renders a FinalReport object into a clean, styled PDF using ReportLab.
Returns raw bytes so the caller can write to disk, serve over HTTP, or
pass directly to Streamlit's download_button without a temp file.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from output.report_schema import FinalReport

# ---------------------------------------------------------------------------
# Brand colours
# ---------------------------------------------------------------------------

NAVY = colors.HexColor("#1D3557")
TEAL = colors.HexColor("#1D9E75")
GRAY = colors.HexColor("#888780")


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def build_styles() -> Dict[str, ParagraphStyle]:
    """Return a dict of named ParagraphStyle objects for the report PDF.

    Styles are built on top of ReportLab's sample stylesheet so that any
    unset attributes fall back to sensible defaults.

    Returns:
        Dict mapping style name strings to ParagraphStyle instances.
    """
    base = getSampleStyleSheet()

    return {
        "title": ParagraphStyle(
            "title",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=NAVY,
            spaceAfter=8,
        ),
        "meta": ParagraphStyle(
            "meta",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            textColor=GRAY,
            spaceAfter=16,
        ),
        "h2": ParagraphStyle(
            "h2",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=NAVY,
            spaceBefore=14,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=15,
            spaceAfter=8,
        ),
        "citation": ParagraphStyle(
            "citation",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=GRAY,
            spaceAfter=4,
        ),
    }


# ---------------------------------------------------------------------------
# Page decorations
# ---------------------------------------------------------------------------

def make_header_footer(canvas: Any, doc: Any) -> None:
    """Draw a branded header and footer on every page.

    Called by ReportLab's ``onFirstPage`` / ``onLaterPages`` hooks.
    Draws outside the document's normal flow so it does not affect
    story layout or pagination.

    Args:
        canvas: ReportLab canvas for the current page.
        doc:    The SimpleDocTemplate instance (provides page dimensions).
    """
    canvas.saveState()

    page_width, page_height = A4

    # --- Header: NAVY bar across the full top ---
    header_height = 10 * mm
    canvas.setFillColor(NAVY)
    canvas.rect(0, page_height - header_height, page_width, header_height, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 8)
    text_y = page_height - header_height + 3 * mm

    canvas.drawString(18 * mm, text_y, "Multi-Agent Research Report")
    page_label = f"Page {doc.page}"
    canvas.drawRightString(page_width - 18 * mm, text_y, page_label)

    # --- Footer: GRAY rule + centred caption ---
    footer_y = 12 * mm
    canvas.setStrokeColor(GRAY)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, footer_y, page_width - 18 * mm, footer_y)

    canvas.setFillColor(GRAY)
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(page_width / 2, footer_y - 4 * mm, "Generated by AI Research Agent")

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Main export function
# ---------------------------------------------------------------------------

def generate_pdf(report: FinalReport) -> bytes:
    """Render a FinalReport to PDF and return the raw bytes.

    Builds a ReportLab story from the report's sections, applies the branded
    styles and page decorations, and returns the compiled PDF as bytes so the
    caller can write to disk, serve over HTTP, or pass to Streamlit's
    ``download_button`` without a temporary file.

    Args:
        report: A fully assembled FinalReport instance.

    Returns:
        Raw PDF bytes.
    """
    buffer = io.BytesIO()
    styles = build_styles()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    story: List[Any] = []

    # Title
    story.append(Paragraph(report.topic, styles["title"]))

    # Metadata line
    meta_text = (
        f"Sources: {report.sources_count} &nbsp;|&nbsp; "
        f"Findings: {report.findings_count} &nbsp;|&nbsp; "
        f"Tokens: {report.token_usage:,} &nbsp;|&nbsp; "
        f"Cost: ${report.cost_usd:.4f} &nbsp;|&nbsp; "
        f"Generated: {report.generated_at}"
    )
    story.append(Paragraph(meta_text, styles["meta"]))

    # Full-width separator under the header block
    story.append(HRFlowable(width="100%", thickness=1, color=TEAL, spaceAfter=10))

    # Sections
    for i, section in enumerate(report.sections):
        story.append(Paragraph(section.heading, styles["h2"]))

        # Split on double newlines into separate paragraphs
        for para_text in section.content.split("\n\n"):
            stripped = para_text.strip()
            if stripped:
                story.append(Paragraph(stripped, styles["body"]))

        # Citations
        for url in section.citations:
            story.append(Paragraph(url, styles["citation"]))

        # Separator between sections (not after the last one)
        if i < len(report.sections) - 1:
            story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY, spaceAfter=6))

    doc.build(
        story,
        onFirstPage=make_header_footer,
        onLaterPages=make_header_footer,
    )

    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from graph.state import ReportSection

    mock_report = FinalReport(
        topic="Retrieval Augmented Generation for Enterprise Applications 2025",
        sections=[
            ReportSection(
                heading="Executive Summary",
                content=(
                    "Retrieval-Augmented Generation (RAG) has become the dominant paradigm "
                    "for grounding large language model outputs in verified enterprise knowledge. "
                    "Organisations adopting RAG report measurable reductions in hallucination rates "
                    "and improved compliance with internal documentation standards.\n\n"
                    "The technology is now considered production-ready for knowledge management, "
                    "customer support, and regulatory reporting use cases across multiple industries."
                ),
                citations=[
                    "https://arxiv.org/abs/2312.10997",
                    "https://example.com/enterprise-rag-2025",
                ],
            ),
            ReportSection(
                heading="Key Findings",
                content=(
                    "Hybrid search combining dense vector retrieval with BM25 keyword matching "
                    "consistently outperforms either approach in isolation across enterprise benchmarks.\n\n"
                    "Domain-specific embedding models fine-tuned on proprietary corpora deliver a "
                    "15-30% improvement in retrieval precision compared to general-purpose models. "
                    "Reranking retrieved chunks prior to generation is now considered a standard "
                    "best practice for production deployments."
                ),
                citations=["https://arxiv.org/abs/2401.00368"],
            ),
        ],
        sources_count=13,
        findings_count=18,
        token_usage=4200,
        cost_usd=4200 * 0.000015,
        generated_at=datetime.now(UTC).isoformat(),
    )

    pdf_bytes = generate_pdf(mock_report)

    output_path = "test_report.pdf"
    with open(output_path, "wb") as f:
        f.write(pdf_bytes)

    print(f"PDF written to   : {output_path}")
    print(f"File size        : {len(pdf_bytes):,} bytes")
